services:
  angular-nginx:
    build: 
      context: frontend
    ports:
      - "4200:4200"
  server: 
    build: 
      context: server
    ports:
      - '5001:5001'
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'kgaps'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password123'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3308:3308'
    expose:
      # Opens port 3306 on the container
      - '3308'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:

networks:
 backend: